var enemyCount = 0, fx = 0, fy = 0, projectileCount = 0, towerCount = 0, fs = 0, towerNum,currentTower, ff = 0,fr=0, ft = 0, i = 0, j = 0, playerLife, waveCount = 0, nearestEnemy = 0,nearestEnemyFuture=0, nearestEnemyX = 0, nearestEnemyY = 0, enemyDistanceX, enemyDistanceY;
var gameTime = 0;
var gold=50;
var upgradeCostBasic= [20,30,40,50,70,90,110,130,150,200,250,300,360,420,480,580,700,850,1000];
var skapemA, skapemB, skapemZ=5, skapemX, skapemY;
var skapemArray = [7, 4];
var audioMain = document.getElementById("wwaudio");
var audioDeath = document.getElementById("enemyDeath");
var audioOof = document.getElementById("oof");
var gameState;
var towerInfoState=false;
var blueTowerClick = 0, redTowerClick = 0, yellowTowerClick = 0, greenTowerClick = 0, clickCount = 0, towerCount = 0, mouseClickX, mouseClickY, mouseX, mouseY;
//var kruhac1;
//var kruhac2;
var path1;
var uwaga1;
var towerMenuDisplayed = 0;
var enemies = [];
var explosions = [];
var projectiles = [];
var towers = [];
var projectileIntervals = [];
var gameStopped = false;
var enemyInRange = false;
var gameAudio = "false";
function resetVariables() {
    enemyCount = 0;
    gold=50;
    waveCount = 0;
    gameTime = 0;
    fx = 0;
    fy = 0;
    projectileCount = 0;
    towerCount = 0;
    fs = 0;
    ff = 0;
    ft = 0;
    i = 0;
}